"""C3: generate and run a sample-replay test file in a separate interpreter.

Third-party client code is imported only by that subprocess, never by specproof itself.
"""

import json
import os
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from specproof.conformance.mapping import Mapping
from specproof.conformance.models import ModelField
from specproof.models.contract import ContractSection
from specproof.models.findings import Evidence, Finding
from specproof.verify.samples import extract_payload

HEADER = '''"""Generated by `specproof conform`. Replays the document's own response samples through
the client's models. Do not edit by hand; regenerate instead."""

import importlib
import json


def _extract(sample, json_path):
    items = [sample["data"]]
    for _ in range(json_path.count("[*]")):
        items = [child for item in items for child in item]
    return items


def _model(dotted):
    module, _, name = dotted.rpartition(".")
    return getattr(importlib.import_module(module), name)
'''

INTROSPECT = """
import dataclasses, importlib, json, sys
from specproof.conformance.models import describe_model
out = {}
for ref in sys.argv[1:]:
    module, _, name = ref.rpartition(".")
    try:
        model = getattr(importlib.import_module(module), name)
        out[ref] = {"fields": [dataclasses.asdict(f) for f in describe_model(model)]}
    except Exception as exc:
        out[ref] = {"error": f"{type(exc).__name__}: {exc}"}
print(json.dumps(out, sort_keys=True))
"""


def replay_test_name(mapping: Mapping) -> str:
    """Stable pytest function name for a mapping."""
    return (
        f"test_replay_{mapping.section_id.replace('-', '_').replace('.', '_')}_{mapping.class_name}"
    )


def generate(mappings: list[Mapping], contracts: dict[str, ContractSection]) -> str:
    """Source of test_sample_replay.py: one test per mapping, deterministic and compilable."""
    parts = [HEADER]
    for mapping in sorted(mappings, key=lambda m: (m.section_id, m.model, m.line)):
        contract = contracts.get(mapping.section_id)
        sample = contract.samples.response if contract is not None else None
        name = replay_test_name(mapping)
        if sample is None:
            parts.append(f"\n\n# {name}: section has no response sample; nothing to replay\n")
            continue
        payload = extract_payload(sample.raw)
        parts.append(
            f"\n\ndef {name}():\n"
            f"    sample = json.loads({payload!r})\n"
            f"    model = _model({mapping.model!r})\n"
            f"    for item in _extract(sample, {mapping.json_path!r}):\n"
            f"        model.model_validate(item)\n"
        )
    return "".join(parts)


def _env(pythonpath: list[Path]) -> dict[str, str]:
    env = dict(os.environ)
    src = Path(__file__).resolve().parents[2]
    env["PYTHONPATH"] = os.pathsep.join([str(src), *(str(p) for p in pythonpath)])
    return env


def introspect(models: list[str], python: str, pythonpath: list[Path]) -> dict[str, dict[str, Any]]:
    """model dotted path -> {"fields": [ModelField...]} or {"error": message}."""
    if not models:
        return {}
    done = subprocess.run(
        [python, "-c", INTROSPECT, *sorted(set(models))],
        capture_output=True,
        text=True,
        env=_env(pythonpath),
        check=False,
    )
    if done.returncode != 0:
        message = (done.stderr.strip().splitlines() or ["introspection failed"])[-1]
        return {m: {"error": message} for m in models}
    raw: dict[str, dict[str, Any]] = json.loads(done.stdout)
    for value in raw.values():
        if "fields" in value:
            value["fields"] = [
                ModelField(
                    f["key"], f["required"], f["type"], tuple(f["enum"]) if f["enum"] else None
                )
                for f in value["fields"]
            ]
    return raw


def _junit(path: Path) -> tuple[dict[str, str], list[str]]:
    """(failed test name -> message, error messages) from a junit XML report."""
    failed: dict[str, str] = {}
    errors: list[str] = []
    root = ET.parse(path).getroot()
    for case in root.iter("testcase"):
        for tag in ("failure", "error"):
            node = case.find(tag)
            if node is not None:
                text = (node.get("message") or "") + "\n" + (node.text or "")
                if tag == "failure" and "ValidationError" in text:
                    failed[case.get("name", "")] = text.strip()
                else:
                    errors.append(f"{case.get('name', '')}: {text.strip()}")
    return failed, errors


def run_replay(
    test_file: Path,
    mappings: list[Mapping],
    contracts: dict[str, ContractSection],
    python: str,
    pythonpath: list[Path],
    client_label: str,
) -> tuple[list[Finding], list[dict[str, str]]]:
    """Run the replay tests; failures are CLIENT_SAMPLE_REJECTED, crashes environment errors."""
    report = test_file.with_suffix(".junit.xml")
    subprocess.run(
        [
            python,
            "-m",
            "pytest",
            str(test_file),
            "-q",
            "-p",
            "no:cacheprovider",
            f"--junitxml={report}",
            "--rootdir",
            str(test_file.parent),
        ],
        capture_output=True,
        text=True,
        env=_env(pythonpath),
        check=False,
    )
    if not report.exists():
        return [], [{"kind": "environment_error", "message": "pytest produced no report"}]
    failed, crashes = _junit(report)
    report.unlink()
    errors = [{"kind": "environment_error", "message": m[:2000]} for m in crashes]
    findings: dict[str, Finding] = {}
    for mapping in mappings:
        message = failed.get(replay_test_name(mapping))
        contract = contracts.get(mapping.section_id)
        if message is None or contract is None or contract.samples.response is None:
            continue
        cite = contract.samples.response.citation
        evidence = sorted(
            [
                Evidence(kind="doc", page=cite.page, quote=cite.quote),
                Evidence(
                    kind="code",
                    file=f"{client_label}/{mapping.file}",
                    line=mapping.line,
                    snippet=_pydantic_summary(message),
                ),
            ],
            key=Evidence.canonical,
        )
        fid = Finding.make_id("CLIENT_SAMPLE_REJECTED", mapping.section_id, mapping.model, evidence)
        findings[fid] = Finding(
            id=fid,
            type="CLIENT_SAMPLE_REJECTED",
            severity="high",
            section_id=mapping.section_id,
            title=(
                f"Model {mapping.class_name} rejects the documented response sample of "
                f"{mapping.section_id}."
            ),
            evidence=evidence,
        )
    return [findings[k] for k in sorted(findings)], errors


def _pydantic_summary(message: str) -> str:
    lines = [line.strip() for line in message.splitlines() if line.strip()]
    start = next((i for i, line in enumerate(lines) if "validation error" in line), 0)
    return " | ".join(lines[start : start + 7])[:600]
